
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 15 21:40:59 CET 2017
//----------------------------------------------------

package oblig1parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ARIT_POW = 46;
  public static final int STRING_LITERAL = 49;
  public static final int REL_LTE = 37;
  public static final int ARIT_PLUS = 42;
  public static final int LOG_OR = 35;
  public static final int SEMI = 29;
  public static final int REF = 9;
  public static final int REL_EQ = 40;
  public static final int NOT = 16;
  public static final int RPAR = 28;
  public static final int ARIT_DIV = 45;
  public static final int BOOL = 20;
  public static final int COMMA = 32;
  public static final int CLASS = 3;
  public static final int BEGIN = 4;
  public static final int TYPE_INT = 23;
  public static final int ASSIGN = 33;
  public static final int IF = 11;
  public static final int DOT = 31;
  public static final int ID = 26;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int ARIT_MUL = 44;
  public static final int TRUE = 18;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NULL = 21;
  public static final int REL_GT = 38;
  public static final int REL_NEQ = 41;
  public static final int TYPE_FLOAT = 25;
  public static final int ARIT_MINUS = 43;
  public static final int REL_GTE = 39;
  public static final int COLON = 30;
  public static final int ELSE = 13;
  public static final int TYPE_STRING = 24;
  public static final int WHILE = 14;
  public static final int THEN = 12;
  public static final int LOG_AND = 34;
  public static final int END = 5;
  public static final int LPAR = 27;
  public static final int FLOAT_LITERAL = 48;
  public static final int FALSE = 19;
  public static final int TYPE_BOOL = 22;
  public static final int REL_LT = 36;
  public static final int COLON_EQUAL = 47;
  public static final int VAR = 6;
  public static final int DEREF = 10;
  public static final int PROCEDURE = 7;
  public static final int DO = 15;
  public static final int INT_LITERAL = 50;
}

